### ISSUE TITLE
semantic versioning & releases

### ISSUE THREAD

**Issue by gaelforget** [brorfred/ocean_clustering#6]
I don't think 0.1 pre-alpha etc makes much sense (https://semver.org). Also, release, pre-release, and git tags are all supported so let's just use that maybe ?

**Comment by brorfred** [comment]
I'm just following the software release syntax, but we can change it to whatever works best. https://en.wikipedia.org/wiki/Software_release_life_cycle

**Comment by gaelforget** [comment]
Thanks
